/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.Controlador;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.modelo.Telefono;

/**
 *
 * @author NANCY
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaCrearUsuario ventanaCrearUsuario;
    private VentanaGestionTelefono ventanaGestionTelefono;
    private VentanaBuscar ventanaBuscar;
    private VentanaIniciarSecion ventanaIniciarSecion;
    
    private Controlador<Persona> controladorPersona;
    private Controlador<Telefono> controladorTelefono;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        controladorPersona= new Controlador<>();
        controladorTelefono = new Controlador<>();
        
        ventanaCrearUsuario= new VentanaCrearUsuario(controladorPersona);
        ventanaGestionTelefono= new VentanaGestionTelefono(controladorPersona,controladorTelefono);
        ventanaBuscar= new VentanaBuscar(controladorPersona,controladorTelefono);
        ventanaIniciarSecion= new VentanaIniciarSecion(controladorPersona, this, ventanaGestionTelefono);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        CrearUsuario = new javax.swing.JMenuItem();
        IniciarSecion = new javax.swing.JMenuItem();
        GestioTelefono = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        CrearUsuario.setMnemonic('o');
        CrearUsuario.setText("Crear Usuario");
        CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioActionPerformed(evt);
            }
        });
        fileMenu.add(CrearUsuario);

        IniciarSecion.setText("Iniciar Secion");
        IniciarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSecionActionPerformed(evt);
            }
        });
        fileMenu.add(IniciarSecion);

        GestioTelefono.setMnemonic('s');
        GestioTelefono.setText("Gestios Telefono");
        GestioTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestioTelefonoActionPerformed(evt);
            }
        });
        fileMenu.add(GestioTelefono);

        Buscar.setMnemonic('a');
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        fileMenu.add(Buscar);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void GestioTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestioTelefonoActionPerformed
        ventanaGestionTelefono.setVisible(true);
        desktopPane.add(ventanaGestionTelefono);
    }//GEN-LAST:event_GestioTelefonoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        ventanaBuscar.setVisible(true);
        desktopPane.add(ventanaBuscar);
    }//GEN-LAST:event_BuscarActionPerformed

    private void CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioActionPerformed
        ventanaCrearUsuario.setVisible(true);
        desktopPane.add(ventanaCrearUsuario);
    }//GEN-LAST:event_CrearUsuarioActionPerformed

    private void IniciarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSecionActionPerformed
        ventanaIniciarSecion.setVisible(true);
        desktopPane.add(ventanaIniciarSecion);
    }//GEN-LAST:event_IniciarSecionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem CrearUsuario;
    private javax.swing.JMenuItem GestioTelefono;
    private javax.swing.JMenuItem IniciarSecion;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
